services:
    events.dispatcher:
        class: 'ThinFrame\Events\Dispatcher'
        tags:
          - { name: 'events.dispatcher'}

    events.sample_listener:
        class: 'ThinFrame\Events\Tests\Samples\SampleListener'
        tags:
          - { name: 'events.listener' }
